server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3
    username: 2RqVc3zsA5nr5Zk.root
    password: sDj0uM4dcN41shtB

#    url: jdbc:mysql://localhost:3306/shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#    username: root
#    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
  jwt:
    secret: change-me-please-change-me-change-me
    expiration-ms: 86400000
  seed:
    admin-email: admin@shop.local
    admin-password: admin123
  cloudinary:
    cloud-name: dpvyfymoq
    api-key: 926618257713912
    api-secret: FeY8t-uNWf1ixdJkEhRBc1Ggq_k
    folder: ${CLOUDINARY_FOLDER:uploads}

logging:
  level:
    org.hibernate.SQL: debug
